### ISSUE TITLE
general discussion of repository structure

### ISSUE THREAD

**Issue by polettif** [r-transit/tidytransit#1]
Hey, I appreciate your effort to separate the different "modules" and I'm looking forward to seeing where this package might end up. As I don't know much about developing R packages, I don't yet understand how this repository and the others (trread, ...) are connected? Is it the same code duplicated and separate or is it automatically cloned/imported in some way?

**Comment by tbuckl** [comment]
hi @polettif i'm also learning when it comes to R packages.

currently i'm thinking that there could be 2 packages:

1) tidytransit - GTFS package with full `sf` dependency.
2) trread - GTFS package with no or only partial `sf` dependency. 

originally i had thought 4 separate packages that could be installed through a meta-package modeled on [tidyverse](https://github.com/tidyverse/tidyverse). 

but @angela-li was (i think rightly) concerned that would be too confusing for users. so i ended up putting all the code from bustt/gtsf/trread/transitfeedr into tidytransit. 

what do you think? in any case, thanks for your question. its a good one.

**Comment by tbuckl** [comment]
@polettif have you ever installed `tidyverse` packages via the tidyverse metapackage?

**Comment by tbuckl** [comment]
@polettif i updated the organization landing page text to describe this better. https://github.com/r-transit/r-transit.github.io/commit/f9fadb21e3230410f133e92f7ff4a1b6d2ac11aa#diff-d680e8a854a7cbad6d490c445cba2eba

sorry for the confusion. let me know if i can do anything else to clarify things.

**Comment by tbuckl** [comment]
@polettif also, if you have any examples how how this kind of thing is handled, whether in R or other languages, i'd be curious to see them. i imagine there's some helpful work on there on this.

**Comment by tbuckl** [comment]
@polettif another potential option is to do the minimum to get map data working, as suggested here by mark: https://github.com/r-transit/trread/issues/5, and just keep development in that 1 package only.

**Comment by polettif** [comment]
Thanks for your answer, couple of points:
- Are the repositories bustt, gtsf and transitfeedr deprecated since they're fully included in tidytransit? If so, this should be noted somewhere and I'd move away from calling tidytransit a package consisting of any other package. Instead I'd say, what the package is able to do. It might end up as the same catch-all package as gtfsr, albeit with a CRAN release.

- We need sf for mapping purposes. However, I'd say mapping is not the core part of transit data and a lot of feeds don't have shapes anyways. So the approach outlined in issue trread#5 seems suitable to me. Or maybe instead of having a full package and a sf-less package, separate feed data manipulation (headway calculations, statistics, maybe a router later on) and mapping. Or have three levels: Reading/Validating, Analyse/Editing and Visualize/Mapping. [I'm starting to see why this discussion seems to be stuck in a loop.](https://github.com/ropensci/gtfsr/issues/53)

- On a minor note: What's the problem with sf? If I understand correctly, it is difficult to install from source but that's not necessary for our purposes?

As far as maintenance goes, I'd say separating modules in files without many interdepencies is a good start.

**Comment by tbuckl** [comment]
hi @polettif i'm going to close this out for now. feel free to reopen if you want to discuss further.
