### ISSUE TITLE
trip_id incompatible types

### ISSUE THREAD

**Issue by mgageo** [r-transit/tidytransit#110]
Hello,
With a small gtfs file, I can't plot th network:
`Calculating headways and spatial features. This may take a while
Calculating route and stop headways.
Erreur : Can't join on 'trip_id' x 'trip_id' because of incompatible types (numeric / character)`

the script

`library(tidytransit)
library(tidyverse)
dsn <- 'https://framagit.org/mgageo/osmdata/raw/master/OSMDATA/gtfs.zip'
fic <- tempfile('gtfs', fileext='.zip')
download.file(dsn, fic,  mode = "wb")
print(sprintf("fic: %s size: %s", fic, file.size(fic)))
tt <- read_gtfs(dsn)
plot(tt)`

Marc

**Comment by polettif** [comment]
Thank you for bringing this up. There seemed to be a problem with UTF-8 BOM. A similar problem to #98) which leads to trip_ids (first column) being read as numeric. I'll fix it with a pull request.

**Comment by mgageo** [comment]
Thank you for this rapid response
