### ISSUE TITLE
Package does not load

### ISSUE THREAD

**Issue by ssulikova** [r-transit/tidytransit#137]
Hi, I  tried installing and loading tidytransit several times today and it  does not seem to work. 

It installs, both when I load the CRAN and the devtools (devtools::install_github("r-transit/tidytransit")) version. 

But when I  try to load the package, I get the following error:  

"Error: package or namespace load failed for ‘tidytransit’:
 object ‘unzip’ is not exported by 'namespace:zip'"

**Comment by polettif** [comment]
This seems to be an issue with your locally installed `zip` package. Tidytransit uses zip::unzip which requires version ≥ 2.0. Does reinstalling zip fix your issue?
```{r}
remove.packages("zip")
install.packages("zip")
library(tidytransit)
```

**Comment by ssulikova** [comment]
It  does! Thanks so much.  I clearly have no clue what I’m doing.



On 10 Dec 2019, at 14:54, Flavio Poletti <notifications@github.com<mailto:notifications@github.com>> wrote:


This seems to be an issue with your locally installed zip package. Tidytransit uses zip::unzip which requires version ≥ 2.0. Does reinstalling zip fix your issue?

remove.packages("zip")
install.packages("zip")
library(tidytransit)
