### ISSUE TITLE
identify source of CRAN check errors, resolve and resubmit 

### ISSUE THREAD

**Issue by tbuckl** [r-transit/tidytransit#145]

**Comment by rsbivand** [comment]
In doing revdep checks for spatial packages, including **sf**, I see errors probably not related to **sf**. I ran the revdep check first with released **dplyr**, then with the state of github/master of **dplyr** from March 31 (a change was made there to remove a regression in **sf** caused by **dplyr**. Regretably, this wasn't what was causing your error, but I thought I'd let you know, as join operations using **sf** objects had been degraded and now work again.

**Comment by tbuckl** [comment]
thanks @rsbivand!

**Comment by krlmlr** [comment]
I'm sorry the tibble update may have triggered removal of tidytransit from CRAN. Let me know if I can help.

**Comment by tbuckl** [comment]
thanks for reaching out @krlmlr. i've been a bit preoccupied with covid, etc, as i'm sure everyone else has too. but glad to hear that the CRAN machine and the tidyverse march on regardless!

i took a look this past weekend and wasn't really sure what version of 'sf', 'tibble', etc, i needed to peg my package at and test it. 

can you give me a spec of what i should be testing against?

in terms of cran resubmission, i assume for that, i deal with them directly?

**Comment by tbuckl** [comment]
@rsbivand is there an example package out there that uses sf, tibble and vctrs that i could look at as an example?

**Comment by krlmlr** [comment]
For the CRAN submission you need CRAN sf (0.9-1) and CRAN tibble (3.0.0). If your package uses dplyr, you might want to ensure that it *also* works with dev dplyr and dev sf (from GitHub).

What errors are you seeing?

**Comment by tbuckl** [comment]
for the moment its 'sf' install errors. but will check back in when i know more.

**Comment by tbuckl** [comment]
all the more reason to remove the 'sf' dependency! ;)

**Comment by tbuckl** [comment]
error below. @polettif can you look into whether this test is critical, or if we can remove it an resubmit to CRAN until we can get this resolved? i'd prefer to just remove the test/function and resubmit to CRAN if it will take a long time to debug. 

```
── 1. Error: travel_times from stop with departures from tra
Assigned data `c("stop0", "Zero", 46.9596, 7.39071, NA, 0)` must be compatible with row subscript `nrow(g2$stops) + 1`.
x 1 row must be assigned.
x Assigned data has 6 rows.
ℹ Only vectors of size 1 are recycled.
Backtrace:
 1. base::`[<-`(...)
 2. tibble:::`[<-.tbl_df`(...)
 3. tibble:::tbl_subassign(x, i, j, value, i_arg, j_arg, substitute(value))
 4. tibble:::vectbl_recycle_rhs(...)
 5. base::tryCatch(...)
 6. base:::tryCatchList(expr, classes, parentenv, handlers)
 7. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 8. value[[3L]](cond)

══ testthat results  ═══════════════════════════════════════
[ OK: 120 | SKIPPED: 0 | WARNINGS: 1 | FAILED: 1 ]
1. Error: travel_times from stop with departures from transfer stops (@test-raptor.R#210) 

Error: testthat unit tests failed
Execution halted

Tests complete
```

**Comment by krlmlr** [comment]
I'm about to introduce a compatibility fix for this particular pattern, which seems to occur far more frequently than anticipated. Going to CRAN in a few days.

**Comment by krlmlr** [comment]
On the other hand, the object used for assignment is a character vector, and we likely want coordinates to be represented as numbers?

**Comment by polettif** [comment]
@krlmlr Thank you. You're right, using a "mixed" vector is sloppy. I changed an additional line in #147 

As for sf/tibble versions: The PR above should fix the tibble 3.0 issue, as far as I can tell. I don't know much about sf though, I'm actually having trouble installing sf's dev version on my machine as well.

**Comment by krlmlr** [comment]
Currently you shouldn't need the dev version of sf. To add a feature column to a tibble, sf must be loaded, otherwise you might see "`x` must be a vector, not a `sfc_.../sfc` object.".

**Comment by tbuckl** [comment]
thanks @polettif i can take a look tonight at whats going on with the failing tests (presumably GDAL/sf install) this weekend if not sooner.

**Comment by tbuckl** [comment]
seems resolved by https://github.com/r-transit/tidytransit/pull/147
