### ISSUE TITLE
Incorrect route linestrings in `.$routes_sf`

### ISSUE THREAD

**Issue by walkerke** [r-transit/tidytransit#15]
Great idea for a package!  However I am noticing some issues with the output on my first use, looking at L train routes in Chicago.  A reproducible example: 

```r
library(tidytransit)
library(mapview)

chicago_gtfs <- read_gtfs("http://www.transitchicago.com/downloads/sch_data/google_transit.zip")

routes <- chicago_gtfs$routes_sf

mapview(routes[routes$route_id == "Pink", ])
```
![image](https://user-images.githubusercontent.com/4872833/44961528-19927e00-aed8-11e8-8b6f-7e700c341b8b.png)

This is the Yellow Line, not the Pink Line.  I'm wondering if some of the rows are getting shuffled when they are converted to simple features?  I've forked and will go through the code but let me know if you have any suggestions.  Thanks!

**Comment by tbuckl** [comment]
thanks @walkerke ill take a look too.

**Comment by tbuckl** [comment]
thanks @walkerke this is a good test case. thats a massive GTFS file.

**Comment by tbuckl** [comment]
i am seeing that too.

**Comment by tbuckl** [comment]
its probably happening in here: 

https://github.com/r-transit/tidytransit/blob/master/R/spatial.R#L32-L37

**Comment by tbuckl** [comment]
@walkerke pretty sure this is just due to the ordering of the processing in there. i think i should be able to fix it today. thanks so much for taking a look! sorry i'm a dufus!

**Comment by tbuckl** [comment]
@walkerke this is looking fixed to me, [thanks](https://github.com/r-transit/tidytransit/blob/master/DESCRIPTION#L15)!

**Comment by tbuckl** [comment]
@walkerke feel free to re-open if its not looking right for you.
