### ISSUE TITLE
package ‘tidytransit’ is not available (for R version 3.5.1) 

### ISSUE THREAD

**Issue by civiliaInc** [r-transit/tidytransit#152]
install.packages("tidytransit")
Warning message:
package ‘tidytransit’ is not available (for R version 3.5.1) 

On which version of R is that safe to install?
Thanks,
Xavier

**Comment by tbuckl** [comment]
@civiliaInc hi Xavier, you'll need to install R 3.6.0 or later to use the current version. 

if you are stuck with 3.5.1, it may be that you could use a previous version of tidytransit, by installing like this:
`
install.packages("tidytransit", version='0.6.0')`

**Comment by civiliaInc** [comment]
Thank you Tom for this fast reply, that fixed the issue.
