### ISSUE TITLE
write a vignette using tidycensus

### ISSUE THREAD

**Issue by tbuckl** [r-transit/tidytransit#16]
based on https://github.com/r-transit/tidytransit/issues/15 its clear that we need better examples to review and test functionality. 

a vignette using tidycensus might be great for this.

**Comment by walkerke** [comment]
great idea @tbuckl!  I've been thinking through ways the packages can work together as well.  Let me know if I can be of help.

**Comment by tbuckl** [comment]
thanks @walkerke! i might ask you to look at a vignette when its ready.

**Comment by tbuckl** [comment]
closing this out for now
