### ISSUE TITLE
transitfeeds.com?

### ISSUE THREAD

**Issue by polettif** [r-transit/tidytransit#172]
Does anyone know what happened to [transitfeeds.com](transitfeeds.com)? The website seems still up but you can't sign in and the linked github repo no longer exists. So it's not possible to create new API keys.

I'm asking because it might be better to remove tidytransit's [transitfeed functions](https://github.com/r-transit/tidytransit/blob/master/R/transitfeeds.R) if the service is no longer available. Are there alternative global GTFS feed lists out there? I know about transit.land which at least showed some activity in 2021.

**Comment by mpadge** [comment]
I saw an article in the transition phase saying that transitfeeds had been "bought out" (pretty sure those were exact words) by transit.land. Suggestion was identical service, new provider name. Hasn't been my experience to date, but seems to be all there is in OS-GTFS for now

**Comment by polettif** [comment]
Ok, thanks @mpadge for the info!

I guess there's no urgency but I'm tempted to remove transitfeed functions for the following reasons: 
- They're not [really covered by tests](https://app.codecov.io/gh/r-transit/tidytransit/blob/master/R/transitfeeds.R) and currently there's no way to improve that since the whole situation seems quite opaque.
- They're not essential to use tidytransit, you just need to get a feed url from _somewhere_. I'd argue actual websites (transit agencies, transit.land or whatever registry there is) are easier to use than some untested package API.
- The [feedlist](https://github.com/r-transit/tidytransit/blob/master/data/feedlist.rda) provided with tidytransit was last updated 3 years (!) ago. Tidytransit is no a feed database and I'd rather not provide any urls at all instead of outdated ones.
