### ISSUE TITLE
remove optional gtfs files on read?

### ISSUE THREAD

**Issue by polettif** [r-transit/tidytransit#19]
While working on #6 I came across specifications for files that are not defined in [gtfs reference](https://developers.google.com/transit/gtfs/reference/) like [directions and stop_attributes](https://github.com/r-transit/tidytransit/blob/c3e748280a6a2ca272ee58b68a81c36ad359b497/R/validate.R#L68). 

I guess there's is an extended or additional specification I'm not aware of?

**Comment by tbuckl** [comment]
@polettif thanks, those do not look like files in the existing spec. we can remove them.

**Comment by tbuckl** [comment]
actually, i'm wondering if it would be better to default to read files like this in case a provider includes them?

**Comment by tbuckl** [comment]
there are examples of extensions to gtfs, such as [GTFS-PLUS](https://github.com/osplanning-data-standards/GTFS-PLUS) that would include unexpected files.

**Comment by tbuckl** [comment]
what do you think @polettif? maybe an default argument like:

```
read_gtfs(feed_url, read_optional=FALSE)
```

**Comment by tbuckl** [comment]
closed by https://github.com/r-transit/tidytransit/pull/22
