### ISSUE TITLE
specify in docs that imported gtfs files need to be in a zipfile

### ISSUE THREAD

**Issue by tbuckl** [r-transit/tidytransit#25]

**Comment by mpadge** [comment]
This shouldn't be necessary, and the whole reading lists of csv's thing is also pretty easy to handle. Main problem for me at the mo is finding time to do this. I'll do my best within the next few weeks, but it might realistically be October or so. Anyway, all great and fabulous work here!

**Comment by tbuckl** [comment]
sounds good thanks @mpadge

**Comment by tbuckl** [comment]
we can always reopen if its unclear in the docs. for context, issue originally prompted by this issue: https://github.com/r-transit/tidytransit/pull/24

**Comment by tbuckl** [comment]
@mpadge of course you would be familiar with lists/dirs of CSVs from https://github.com/ropensci/bikedata :)
