### ISSUE TITLE
Package description on github

### ISSUE THREAD

**Issue by polettif** [r-transit/tidytransit#30]
@tbuckl Should we change the package description on github? I don't think the package being sf compatible is its main focus. I'd suggest something like on tidytransit.r-transit.org:
"tidytransit reads the General Transit Feed Specification (GTFS) into tidyverse and simple features dataframes. Use tidytransit to map transit stops and routes, calculate transit frequencies, and validate transit feeds."

**Comment by tbuckl** [comment]
done! a bit long maybe? i can try to reword later
