### ISSUE TITLE
Use data.table to read feeds?

### ISSUE THREAD

**Issue by mpadge** [r-transit/tidytransit#49]
``` r
library(tidytransit)
library (magrittr)
f <- list.files (getwd (), full.names = TRUE)
filename <- f [grep ("VBB", f)] # GTFS for Berlin-Brandenburg Transport - it's huge!
get_df <- function (filename)
{
    flist <- file.path (utils::unzip (filename, list = TRUE)$Name)
    res <- list ()
    for (i in seq (flist))
    {
        cmd <- paste0 ("unzip -p \"", filename, "\" \"", flist [i], "\"")
        res [[i]] <- data.table::fread (cmd = cmd, showProgress = FALSE) %>%
            as.data.frame ()
    }
    names (res) <- strsplit (flist, ".txt")
    return (res)
}
rbenchmark::benchmark (
                       dat <- read_gtfs (filename, local = TRUE),
                       dat <- get_df (filename),
                       replications = 1)
#>                                       test                       replications elapsed relative   user.self sys.self user.child sys.child
#> 2                                dat <- get_df(filename)            1    3.463     1.00      6.678     0.432      1.745     0.312
#> 1 dat <- read_gtfs(filename, local = TRUE)            1  31.411     9.07    30.701    0.645      0.000     0.000
```

<sup>Created on 2019-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

GTFS feeds can be enormous, and `data.table` makes a pretty huge difference - it'll read a feed nearly ten times faster!

---

This is also by way of starting a separate conversation about the potential future merging of [`gtfs-router`](https://github.com/ATFutures/gtfs-router) into this package. It seems like the obvious place for it, and the primary usage for `tidytransit` if it were available is surely likely to be transit routing? You could then check out your transit options from within the comfort of your R session!

**Comment by tbuckl** [comment]
thanks @mpadge this simple change decreased the devtools::check build time for the package in half.
