### ISSUE TITLE
Remove _df and _sf suffix from dataframes and simple features data frames

### ISSUE THREAD

**Issue by polettif** [r-transit/tidytransit#54]
Is there a compelling reason to use the _df suffix for the data frames (e.g. `gtfs$stops_df`)?

**Comment by tbuckl** [comment]
@polettif i think this makes sense. i'd like to make other breaking changes as well such as: https://github.com/r-transit/tidytransit/issues/56

**Comment by tbuckl** [comment]
@polettif if you want to implement this i'd be happy to merge. i'm also fine to leave it as it is. 

if we do this i think we should be very clear at lots of points in the documentation about the change. 

that way we can avoid user more questions about api changes, though we should expect those anyway.
