### ISSUE TITLE
Plot example not working

### ISSUE THREAD

**Issue by polettif** [r-transit/tidytransit#55]
Based on [this stackoverflow question](https://stackoverflow.com/questions/52892418/plotting-gtfs-object-routes-with-tidytransit-in-r).

```r
local_gtfs_path <- system.file("extdata", 
                              "google_transit_nyc_subway.zip", 
                              package = "tidytransit")
nyc <- read_gtfs(local_gtfs_path, 
                local=TRUE)
plot(nyc)
```

with the plot function:

```r
tidytransit:::plot.gtfs <- function (x, ...) {
    dots = list(...)
    routes_sf_frequencies <- x$routes_sf %>% dplyr::inner_join(x$routes_frequency_df, 
        by = "route_id") %>% dplyr::select(median_headways, mean_headways, 
        st_dev_headways, stop_count)
    plot(routes_sf_frequencies)
}
```

The problem seems to be twofold: routes_sf is missing by default and the headway calculations haven't been done.

**Comment by tbuckl** [comment]
thanks for finding this @polettif! this is a great example of how user might experience an api breaking change. i submitted a PR for this.
