### ISSUE TITLE
make get_* function names more consistent

### ISSUE THREAD

**Issue by tbuckl** [r-transit/tidytransit#56]
make `routes_df_as_sf` match the naming of `get_route_frequency`. this would be more logical/easier to understand. so, for example, `get_route_geometry`.

**Comment by polettif** [comment]
In addition, functions that return a modified `gtfs_obj`, mostly after they added a data frame, (like `validate_gtfs`, `gtfs_as_sf` or `set_hms_times`) should be named differently than methods that return a single data frame or something else but not the whole feed (like `get_date_service_table`).

As for your example, I'd avoid the `get_*` if the function returns a gtfs_obj.

**Comment by tbuckl** [comment]
@polettif i like the idea of hinting at the returned object in the function name--so get_* returns single dataframes and something else returns full gtfs objects? what about gtfs_* returns a full gtfs object? then the three example you gave get prefixed/reordered to have gtfs_* at the front?

**Comment by tbuckl** [comment]
@polettif i'm going to close the get_* part of this issue out and open another for gtfs_* objects or whatever we want to call it.
