### ISSUE TITLE
think about more efficient representations of gtfs 

### ISSUE THREAD

**Issue by tbuckl** [r-transit/tidytransit#68]
https://medium.com/transit-app/how-we-shrank-our-trip-planner-till-it-didnt-need-data-84984ca56663

**Comment by mpadge** [comment]
wow, that's great! Thanks for the link. It's not open source, however, at least not on [their github](https://github.com/TransitApp), so only really of use for them. Very interesting nonetheless.

**Comment by tbuckl** [comment]
@mpadge indeed, upon reflection there's not much of actionable substance in that article. sorry about that! i totally fell for the clickbait! but still an interesting idea.
