### ISSUE TITLE
Stops and routes frequency calculation fails when routes have their own unique service ID's (e.g. Barcelona)

### ISSUE THREAD

**Issue by orlandoandradeb** [r-transit/tidytransit#72]
Hello everyone  I am trying to plot the frecuency of buses that pass trough each stop. 

The library suppose to add these data  when I  write  frecuency true  like below: 
gtfs <-read_gtfs("gtfs.zip", local=TRUE, geometry = TRUE,  frequency=TRUE)

Theorically I will get a new data with the frecuency of buses per stop. However I get a error in the console that says : 

Warning message:
In get_route_frequency(gtfs_obj) : failed to calculate frequency--
            try passing a service_id from calendar_df

becasue this  I cant get that ifnormation (I get the data frame but without that data), I have also try to get it using "get_stop_frequency" without luck. 

Can someone help me ? 
Thank you all

**Comment by tbuckl** [comment]
hi @orlandoandradeb can you provide a link to the GTFS.zip file you reference above?

**Comment by orlandoandradeb** [comment]
Hello  @tbuckl  sure you can get them here: 
https://transitfeeds.com/p/transports-metropolitans-de-barcelona-tmb/995/latest/download

**Comment by tbuckl** [comment]
hi @orlandoandradeb thanks for submitting this. i'm not immediately sure why frequency calculation is failing on this GTFS data. 

BUT, this feed already includes a "frequencies" data frame, with some pre-calculated route frequencies. these are probably better than what tidytransit would have estimated anyway.  

lets say you want to look at frequencies per route. you could do this:

```
bc_gtfs <- read_gtfs("/Users/tbuck/Downloads/gtfs.zip", local=TRUE)
bc_gtfs$trips %>% 
  filter(trip_id %in% bc_gtfs$frequencies$trip_id) %>%
  left_join(bc_gtfs$frequencies) %>%
  left_join(bc_gtfs$routes) %>%
  select(route_id, route_short_name, route_long_name, headway_secs)
```

ill look into why tidytransit fails on this feed sometime this weekend but maybe you can find what you need from the frequencies table? you could also join it to simple/spatial features if you want to.

**Comment by tbuckl** [comment]
here's how you would plot the frequencies:

```
bc_gtfs$routes_sf <- get_route_geometry(bc_gtfs)

named_route_frequencies <- bc_gtfs$trips %>% 
  filter(trip_id %in% bc_gtfs$frequencies$trip_id) %>%
  left_join(bc_gtfs$frequencies) %>%
  left_join(bc_gtfs$routes) %>%
  select(route_id, route_short_name, route_long_name, headway_secs)

routes_freq_sf<- bc_gtfs$routes_sf %>% left_join(named_route_frequencies)

plot(routes_freq_sf, col = routes_freq_sf$headway_secs)
```

**Comment by tbuckl** [comment]
@orlandoandradeb it seems like maybe barcelona uses a different "service id" for each route in this gtfs feed. 

you might want to join the`service` data frame to whatever your unit of interest is (for example, routes), in order to filter any of the tables above. 

that may also be why frequency calculation is failing. 

the frequency calculation in here tries to make a guess about a single service id that describes a typical weekday. but it seems like that breaks on this feed, given the relationship between service ID's and routes.

**Comment by orlandoandradeb** [comment]
Hello @tbuckl   I really appreciate your answer. With the code that you wrote I was avialabe to plot the frecuencies of the routes.  I have try to modifed  that code to get the stops frecuency but it has been a bit complicate for me. 

I tryed with more GTFS with berlin, Vancouver and Madrid and I always got the same error, I mean I get the data frame well  but the function of stops frecuencies and routes frecuencies doesnt work . The library seems like doesnt make that part of the code well. 
Thnaks agian for the  help

**Comment by tbuckl** [comment]
thanks for the feedback @orlandoandradeb!

**Comment by tbuckl** [comment]
@orlandoandradeb also, if you have time, please consider sharing some of the code you wrote (for berlin, vancouver, madrid, etc), so that others can benefit from what you've learned here.

**Comment by tbuckl** [comment]
hi @orlandoandradeb i just checked Translink's GTFS feed and the frequency calculations seem to work.

for example:
```
vc_g <- read_gtfs("https://translinkweb.blob.core.windows.net/gtfs/History/2019-03-22/google_transit.zip", frequency = TRUE)
```

can you provide links to the other GTFS feeds that did not work for frequency calculation?

**Comment by tbuckl** [comment]
@orlandoandradeb Madrid also works. 

e.g. 
```
madrid_g <- read_gtfs("http://servicios.emtmadrid.es:8080/GTFS/transitEMT.zip", frequency=TRUE)
```

**Comment by orlandoandradeb** [comment]
Hello @tbuckl  thanks again. 
It so weird.      I understand that the library can read the files from a local direction or taking a url like in your example.   So, again theorically  just with copy and paste  the code  you posted above I will have to  convert thoses feeds in data frame but not. 

I got this: 

![Captura de pantalla (37)_LI](https://user-images.githubusercontent.com/48104481/54874605-4d6dbc00-4db4-11e9-9c26-436039942718.jpg)

**Comment by orlandoandradeb** [comment]
I run the library, I  put the function : read_gtfs with the url and with frecuency: TRUE 

I am not really  expert in R , but I don´t see something wrong with the procedure.

**Comment by orlandoandradeb** [comment]
about the code. I will be glad to uploadto share when I finish it. I have  made some nice graphs but  I have to do much more things first.

**Comment by tbuckl** [comment]
@orlandoandradeb weird indeed! thanks for the screenshot.

**Comment by tbuckl** [comment]
@orlandoandradeb one thing to keep in mind is that some of the feeds you want to work with are very large and detailed. 

previously, when i've needed to run frequency calculations on large feeds quickly, i will rent time on a machine with a lot of memory and then run an r studio cloud instance on it. here's [a guide](https://github.com/BayAreaMetro/Data-Analysis-Projects/tree/master/rstudio-server) on how to get started with something like that. it might be challenging to pick up quickly though.

**Comment by orlandoandradeb** [comment]
I am starting to think that is something related with versions of R. 
I tried to do it in a Mac with worse results, the library doesn't  even run  haha  :/

I tried with my Windows computer with smaller feeds too such as Mexico City : https://transitfeeds.com/p/mexico-city-federal-district-government/70

with the same result,  it give me the data frame  but not the extra column of routes and stops frequency. 



![Screen Shot 2019-03-23 at 10 07 54 PM](https://user-images.githubusercontent.com/48104481/54874823-6bd5b680-4db8-11e9-991b-ed57b1d518d0.png)



![54525725_539090039949952_7735039583867371520_n](https://user-images.githubusercontent.com/48104481/54874871-6af15480-4db9-11e9-8935-90ce04337b31.png)

**Comment by orlandoandradeb** [comment]
I found this code  for make a heat map of stops frecuncies : 


stops_freq = 
inner_join(stop_times,stops,by=c("stop_id")) %>% 
inner_join(trips,by=c("trip_id")) %>%
inner_join(calendar,by=c("service_id")) %>%
select(stop_id,stop_name,stop_lat,stop_lon) #%>%


stat_density2d(data = stops_freq, aes(x = stop_lon, y = stop_lat, alpha=..level..), size = .5, color='black', bins=5, geom = "polygon", fill='blue') s


It looks good, it gives me an enviroment object that I guess that have correct the data.  I am trying to plot it or convert in data frame to plot it easier.

**Comment by orlandoandradeb** [comment]
I got it  now with this: 




stops_freq = 
  
  inner_join(stop_times,stops,by=c("stop_id")) %>%
  
  inner_join(trips,by=c("trip_id")) %>%
  
  inner_join(calendar,by=c("service_id")) %>%
  
  select(stop_id,stop_name,stop_lat,stop_lon) %>%
  
  group_by(stop_id,stop_name,stop_lat,stop_lon) %>%
  
  summarize(count=n())

**Comment by orlandoandradeb** [comment]
It works well  😀 😀 😀😀 🎉 🎉 🎉 🎉

**Comment by tbuckl** [comment]
@orlandoandradeb glad you found something that worked! thanks for posting the code. 

i think i've had that rlang error before. i can't recall what caused it, but i think it had to do with how i had my environment set up.

**Comment by polettif** [comment]
> @orlandoandradeb it seems like maybe barcelona uses a different "service id" for each route in this gtfs feed.
>  [...] 
> the frequency calculation in here tries to make a guess about a single service id that describes a typical weekday. but it seems like that breaks on this feed, given the relationship between service ID's and routes.

It's quite often the case that service_ids don't indicate any pattern by themselves. Some feeds might even use a service_id for each day or each trip. A more general approach is to extract the "timetable date slots" (e.g. weekdays, weekends. holidays and so on) for each trip from the actual dates it runs on. FWIW I'm working on a vignette on this.

**Comment by tbuckl** [comment]
@polettif awesome! looking forward to that vignette. 

to make the frequency functions more robust against these cases, it could be that we just add some conditional logic [here](https://github.com/r-transit/tidytransit/blob/master/R/frequencies.R#L36-L44) to handle cases where a single service id doesn't relate to "trips" across the network.

**Comment by tbuckl** [comment]
oh sorry @polettif i just noticed that you've already committed [a draft of that vignette](https://github.com/r-transit/tidytransit/blob/bf8a3cb40d1cd5d7f1a487308ee4a1c8f277a26f/vignettes/timetable.Rmd).

**Comment by tbuckl** [comment]
the long term plan is to deprecate the frequency flag and direct users through usage of service id selection #108
