### ISSUE TITLE
if a frequencies data frame exists, then use that by default instead of calculating another one

### ISSUE THREAD

**Issue by tbuckl** [r-transit/tidytransit#73]
see https://github.com/r-transit/tidytransit/issues/72

**Comment by mpadge** [comment]
Do you know of any example data sets that have a frequencies table? I haven't been able to find any yet...

**Comment by tbuckl** [comment]
@mpadge yeah, barcelona seems to have one: https://transitfeeds.com/p/transports-metropolitans-de-barcelona-tmb/995/latest/download
