### ISSUE TITLE
memory limitations for large feeds--prompt users

### ISSUE THREAD

**Issue by tbuckl** [r-transit/tidytransit#77]

**Comment by mpadge** [comment]
`data.table` should largely take care of this, because it allows out-of-memory access. Or if you want, I could easily code up a C++ version that would only read `stop_times.txt` line-by-line, so it wouldn't have to be pulled into memory. Let me know, or give me a good example of such a huge feed, and I'll happily delve in.

**Comment by tbuckl** [comment]
@mpadge i did not know that about data.table. 

i think the VBB feed is probably a good example of a large feed. 

really any non-US transit system should be a good example ;)

i assume that would also require re-writing the [frequency calculation](https://github.com/r-transit/tidytransit/blob/master/R/frequencies.R) and service logic (currently in in dplyr) for data.table. 

sounds like it might be a non-trivial amount of work!

**Comment by tbuckl** [comment]
@mpadge on the other hand maybe the `tidy-` prefix for this package should indicate to users already that we are using dplyr, and therefore have not leveraged `data.table` and that, therefore, this package is and memory-hungry (but not [lazy](https://en.wikipedia.org/wiki/Lazy_evaluation)?)

**Comment by tbuckl** [comment]
@mpadge also, it would be cool to see a plot of size of GTFS feed vs ridership.

**Comment by mpadge** [comment]
Scanning `stop_times.txt` in C++ is really very trivial, and can be done in relatively few lines of C++. But it is likely that `data.table` might do the job anyway. I've yet to encounter any feed too big to hold in memory - even Transport for London all fits in memory (although that's in a custom, non-GTFS format), and I doubt there are bigger ones than that. VBB fits easily. Maybe Barcelona is bigger? I'll have a play around ...

**Comment by stmarcin** [comment]
If you need a big feed for testing, the data from the Netherlands might be useful: http://gtfs.ovapi.nl/nl/ 
Its a combined feed for all the country and includes several agencies. 
Note that there is no `calendar.txt` and only `calendar_dates.txt` file (`stop_times.txt` is about 900 MB)

**Comment by tbuckl** [comment]
closing. see https://github.com/r-transit/tidytransit/pull/107 for why and a potential future fix if desired.
