### ISSUE TITLE
Encourage people to download development version on README.md

### ISSUE THREAD

**Issue by angela-li** [r-transit/tidytransit#8]
Since the version on CRAN is a bit different, in terms of functions available. We want people to keep up with our newest developments!

**Comment by tbuckl** [comment]
yes definitely. i do hate to tell people they *should* be using devtools/github, which can be hard if they don't admin their computer. might make sense to clarify that the reference and docs online are for development version and that the cran version has different docs.

**Comment by tbuckl** [comment]
closed by https://github.com/r-transit/tidytransit/commit/44ec217c6705058ae2f8f64c44e25188c72badb4
