### ISSUE TITLE
Add CONTRIBUTING.md and CONDUCT.md

### ISSUE THREAD

**Issue by angela-li** [r-transit/tidytransit#9]
It's always good to have something explicit! Use ggplot2 [CONTRIBUTING.md](https://github.com/tidyverse/ggplot2/blob/master/CONTRIBUTING.md) and sf [CONDUCT.md](https://github.com/r-spatial/sf/blob/master/CONDUCT.md) as examples.

**Comment by tbuckl** [comment]
done https://github.com/r-transit/tidytransit/commit/bc976747ef1cadbc74c2be1ee1b6363fbcefea8b
