### ISSUE TITLE
read_gtfs / encoding problem (?)

### ISSUE THREAD

**Issue by stmarcin** [r-transit/tidytransit#98]
Hello!
First - thanks for the great package. 
I am trying to read_gtfs feed for metro Madrid (http://datos.crtm.es/). When reading, I got the following comment:

> Error in shape_route_service(gtfs_obj, route_ids = route_ids, service_ids = service_ids) : 
  No provided Route ID(s) were found. 
          Please provide valid Route IDs.
In addition: Warning messages:
1: In gtfs_validate(gtfs_obj, quiet = quiet) :
  Invalid feed. Missing required field(s): service_id, service_id, fare_id, fare_id, feed_publisher_name, trip_id, route_id, shape_id, stop_id, trip_id, route_id
2: Unknown or uninitialised column: 'route_id'. 
3: Unknown or uninitialised column: 'route_id'. 
4: Unknown or uninitialised column: 'route_id'. 

I guess, the problem is related to file encoding (the name of the first column get some strange prefix, e.g. `route.txt:`  file gets: `ď.żroute_id` and it applies to all txt files), however, the file is supposed to be UTF-8. I would appreciate any idea how to solve this issue.
[M4_metro.zip](https://github.com/r-transit/tidytransit/files/3222776/M4_metro.zip)

**Comment by polettif** [comment]
I couldn't reproduce it on a Mac but the error on Windows points indeed to an encoding problem. Apparently, these files use a BOM at the beginning which leads to these weird prefixes. Setting the global encoding to UTF-8-BOM appears fix the issue:
```{r}
options(encoding = "UTF-8-BOM")
gtfs <- read_gtfs("M4_metro.zip")
```
However, BOMs should be handled somewhere during reading, I'll look into it.

**Comment by stmarcin** [comment]
Thanks!
Problem solved.
